ARG BASE_IMAGE_TAG=latest
FROM glregistry.boost.open.global/rennes-metropole/rudi/rudi/microservice:$BASE_IMAGE_TAG

ADD rudi-microservice-gateway-facade.jar /opt/rudi/microservice.jar
ADD gateway.yml /opt/rudi/config/microservice/
