---
swagger: "2.0"
info:
  description: "This document specifies a **RESTful API** for WSO2 **API Manager**\
    \ - Admin Portal.\nPlease see [full swagger definition](https://raw.githubusercontent.com/wso2/carbon-apimgt/v6.5.176/components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/resources/admin-api.yaml)\
    \ of the API which is written using [swagger 2.0](http://swagger.io/) specification.\n"
  version: "v1.2"
  title: "WSO2 API Manager - Admin"
  contact:
    name: "WSO2"
    url: "http://wso2.com/products/api-manager/"
    email: "architecture@wso2.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "apis.wso2.com"
basePath: "/api/am/admin/v1"
schemes:
  - "https"
paths:
  /throttling/policies/application:
    get:
      tags:
        - "Application Policy (Collection)"
      summary: "Get all Application Throttling Policies"
      description: "Retrieves all existing application throttling policies.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:tier_view"
    post:
      tags:
        - "Application Policy (Collection)"
      summary: "Add an Application Throttling Policy"
      description: "This operation can be used to add a new application level throttling\
        \ policy.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:tier_manage"
  /throttling/policies/application/{policyId}:
    get:
      tags:
        - "Application Policy (Individual)"
      summary: "Get an Application Policy"
      description: "Retrieves an Application Policy.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:tier_view"
    put:
      tags:
        - "Application Policy (Individual)"
      summary: "Update an Application Throttling policy"
      description: "Updates an existing Application level throttling policy. Upon\
        \ succesfull, you will receive the updated application policy as the response.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:tier_manage"
    delete:
      tags:
        - "Application Policy (Individual)"
      summary: "Delete an Application Throttling policy"
      description: "Deletes an Application level throttling policy.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:tier_manage"
  /policies/mediation:
    get:
      tags:
        - "Mediation Policy (Collection)"
      summary: "Get all global mediation policies\n"
      description: "This operation provides you a list of available all global level\
        \ mediation policies.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:mediation_policy_view"
      x-wso2-curl: "curl -k -H \"Authorization: Bearer 36a1644d-16c8-3f10-af2a-cedac82a6f21\"\
        \ https://localhost:9443/api/am/admin/v1/policies/mediation"
      x-wso2-request: "GET https://localhost:9443/api/am/admin/v1/policies/mediation\r\
        \nAuthorization: Bearer 36a1644d-16c8-3f10-af2a-cedac82a6f21"
      x-wso2-response: "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n\
        {\r\n   \"count\": 13,\r\n   \"next\": null,\r\n   \"previous\": null,\r\n\
        \   \"list\":    [\r\n            {\r\n         \"name\": \"debug_json_fault\"\
        ,\r\n         \"id\": \"563de8f3-dd1d-4ec7-afc2-d158c663ed34\",\r\n      \
        \   \"type\": \"fault\"\r\n      },\r\n            {\r\n         \"name\"\
        : \"json_fault\",\r\n         \"id\": \"f9c36f4d-a2b6-41e7-b311-d358a47916be\"\
        ,\r\n         \"type\": \"fault\"\r\n      },\r\n            {\r\n       \
        \  \"name\": \"debug_json_fault2\",\r\n         \"id\": \"378169d3-6fd2-427f-b0db-0f378e89ccea\"\
        ,\r\n         \"type\": \"fault\"\r\n      },\r\n            {\r\n       \
        \  \"name\": \"json_to_xml_in_message\",\r\n         \"id\": \"3921225b-7918-4b95-a851-22c4e4e3e911\"\
        ,\r\n         \"type\": \"in\"\r\n      },\r\n            {\r\n         \"\
        name\": \"debug_in_flow\",\r\n         \"id\": \"2bc15f93-4455-4763-89b8-83600fb9d731\"\
        ,\r\n         \"type\": \"in\"\r\n      },\r\n            {\r\n         \"\
        name\": \"log_in_message\",\r\n         \"id\": \"4d287cca-76ab-44ca-b22e-919fc27c50e3\"\
        ,\r\n         \"type\": \"in\"\r\n      },\r\n            {\r\n         \"\
        name\": \"preserve_accept_header\",\r\n         \"id\": \"3776b215-b3bc-40b6-bdcb-06efa7de64be\"\
        ,\r\n         \"type\": \"in\"\r\n      },\r\n            {\r\n         \"\
        name\": \"xml_to_json_in_message\",\r\n         \"id\": \"50ac2002-769e-4f90-8549-6d0248dff7d2\"\
        ,\r\n         \"type\": \"in\"\r\n      },\r\n            {\r\n         \"\
        name\": \"xml_to_json_out_message\",\r\n         \"id\": \"2af75853-ed75-4d25-81aa-0ebbeca691ea\"\
        ,\r\n         \"type\": \"out\"\r\n      },\r\n            {\r\n         \"\
        name\": \"json_to_xml_out_message\",\r\n         \"id\": \"d9fa3ffc-f6b6-4171-ab97-eb44196cb66e\"\
        ,\r\n         \"type\": \"out\"\r\n      },\r\n            {\r\n         \"\
        name\": \"debug_out_flow\",\r\n         \"id\": \"260b7701-4071-46bd-9b66-900ac6fffed6\"\
        ,\r\n         \"type\": \"out\"\r\n      },\r\n            {\r\n         \"\
        name\": \"apply_accept_header\",\r\n         \"id\": \"15c17c2f-33e3-4c37-a262-04dfa49983a4\"\
        ,\r\n         \"type\": \"out\"\r\n      },\r\n            {\r\n         \"\
        name\": \"log_out_message\",\r\n         \"id\": \"d37dca41-c048-492a-82cf-9a2292c6fff0\"\
        ,\r\n         \"type\": \"out\"\r\n      }\r\n   ]\r\n}"
    post:
      tags:
        - "Mediation Policy (Collection)"
      summary: "Add a global mediation policy"
      description: "This operation can be used to add a new global mediation policy.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:mediation_policy_create"
      x-wso2-curl: "curl -k -H \"Authorization: Bearer 45c1e774-7d5a-3e2a-b76c-53f786efac6b\"\
        \ -H \"Content-Type: application/json\" -X POST -d @data.json \"https://localhost:9443/api/am/admin/v1/policies/mediation\""
      x-wso2-request: "POST https://localhost:9443/api/am/admin/v1/policies/mediation\r\
        \nContent-Type: application/json\r\nAuthorization: Bearer 45c1e774-7d5a-3e2a-b76c-53f786efac6b\r\
        \n\r\n{\r\n   \"name\": \"add_custom_header_fault\",\r\n   \"type\": \"fault\"\
        ,\r\n   \"config\": \"<sequence xmlns=\\\"http://ws.apache.org/ns/synapse\\\
        \" name=\\\"add_custom_header_fault\\\">\\n    <property name=\\\"CustomHeader\\\
        \" scope=\\\"transport\\\" value=\\\"example\\\"/>\\n<\\/sequence>\\n\"\r\n\
        }"
      x-wso2-response: "HTTP/1.1 201 Created\r\nLocation: https://localhost:9443/api/am/admin/v1/registry/resource/_system/governance/apimgt/customsequences/fault/add_custom_header_fault.xml\r\
        \nContent-Type: application/json\r\n\r\n{\r\n   \"id\": \"2e5cebbb-e48c-4345-a912-1f0a2058aa05\"\
        ,\r\n   \"name\": \"add_custom_header_fault\",\r\n   \"type\": \"fault\",\r\
        \n   \"config\": \"<sequence xmlns=\\\"http://ws.apache.org/ns/synapse\\\"\
        \ name=\\\"add_custom_header_fault\\\">\\n    <property name=\\\"CustomHeader\\\
        \" scope=\\\"transport\\\" value=\\\"example\\\"/>\\n<\\/sequence>\\n\"\r\n\
        }"
  /policies/mediation/{mediationPolicyId}:
    get:
      tags:
        - "Mediation Policy (Individual)"
      summary: "Get a global mediation policy"
      description: "This operation can be used to retrieve a particular global mediation\
        \ policy.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:mediation_policy_view"
      x-wso2-curl: "curl -k -H \"Authorization: Bearer da3b0521-5adb-3edc-8ab9-295b4c34c809\"\
        \ https://localhost:9443/api/am/admin/v1/policies/mediation/2e5cebbb-e48c-4345-a912-1f0a2058aa05"
      x-wso2-request: "GET https://localhost:9443/api/am/admin/v1/policies/mediation/2e5cebbb-e48c-4345-a912-1f0a2058aa05\n\
        Authorization: Bearer da3b0521-5adb-3edc-8ab9-295b4c34c809"
      x-wso2-response: "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\n   \"\
        id\": \"2e5cebbb-e48c-4345-a912-1f0a2058aa05\",\n   \"name\": \"add_custom_header_fault\"\
        ,\n   \"type\": \"fault\",\n   \"config\": \"<sequence xmlns=\\\"http://ws.apache.org/ns/synapse\\\
        \" name=\\\"add_custom_header_fault\\\">\\n    <property name=\\\"CustomHeader\\\
        \" scope=\\\"transport\\\" value=\\\"example\\\"/>\\n<\\/sequence>\\n\"\n}"
    put:
      tags:
        - "Mediation Policy (Individual)"
      summary: "Update a global mediation policy"
      description: "This operation can be used to update an existing global mediation\
        \ policy.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:mediation_policy_create"
      x-wso2-curl: "curl -k -H \"Authorization: Bearer 58b3b072-74bb-3381-a213-ce1ca2857c2f\"\
        \ -H \"Content-Type: application/json\" -X PUT -d @data.json https://localhost:9443/api/am/admin/v1/policies/mediation/8242d72c-b7d7-4b51-9098-d24bd4a5ea3a"
      x-wso2-request: "PUT https://localhost:9443/api/am/admin/v1/policies/mediation/76cc38e4-f41a-457a-a987-3a677c290dc6\n\
        Content-Type: application/json\nAuthorization: Bearer 58b3b072-74bb-3381-a213-ce1ca2857c2f\n\
        \n{\n   \"name\": \"add_custom_header_fault\",\n   \"type\": \"fault\",\n\
        \   \"config\": \"<sequence xmlns=\\\"http://ws.apache.org/ns/synapse\\\"\
        \ name=\\\"add_custom_header_fault\\\">\\n    <property name=\\\"CustomHeader\\\
        \" scope=\\\"transport\\\" value=\\\"example\\\"/>\\n<\\/sequence>\\n\"\n\
        }\n"
      x-wso2-response: "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\n   \"\
        id\": \"8242d72c-b7d7-4b51-9098-d24bd4a5ea3a\",\n   \"name\": \"add_custom_header_fault\"\
        ,\n   \"type\": \"fault\",\n   \"config\": \"<sequence xmlns=\\\"http://ws.apache.org/ns/synapse\\\
        \" name=\\\"add_custom_header_fault\\\">\\n    <property name=\\\"CustomHeader\\\
        \" scope=\\\"transport\\\" value=\\\"example\\\"/>\\n<\\/sequence>\\n\"\n}"
    delete:
      tags:
        - "Mediation Policy (Individual)"
      summary: "Delete a global mediation policy"
      description: "This operation can be used to delete an existing global mediation\
        \ policy providing the Id of the mediation policy.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:mediation_policy_create"
      x-wso2-curl: "curl -k -H \"Authorization: Bearer fb2a0784-f60c-3276-8fde-5b0f70e61ecc\"\
        \ -X DELETE https://localhost:9443/api/am/admin/v1/policies/mediation/2c85844c-588f-4000-9ce5-f4cdc422cc8b"
      x-wso2-request: "DELETE https://localhost:9443/api/am/admin/v1/policies/mediation/2c85844c-588f-4000-9ce5-f4cdc422cc8b\n\
        Content-Type: application/json\nAuthorization: Bearer 58b3b072-74bb-3381-a213-ce1ca2857c2f"
      x-wso2-response: "HTTP/1.1 200 OK"
  /throttling/policies/subscription:
    get:
      tags:
        - "Subscription Policy (Collection)"
      summary: "Get all Subscription Throttling Policies"
      description: "This operation can be used to retrieve all Subscription level\
        \ throttling policies.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:tier_view"
    post:
      tags:
        - "Subscription Policy (Collection)"
      summary: "Add a Subscription Throttling Policy"
      description: "This operation can be used to add a Subscription level throttling\
        \ policy specifying the details of the policy in the payload.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:tier_manage"
  /throttling/policies/subscription/{policyId}:
    get:
      tags:
        - "Subscription Policy (Individual)"
      summary: "Get a Subscription Policy"
      description: "Retrieve a single subscription-level throttling policy. We should\
        \ provide the Id of the policy as a path parameter.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:tier_view"
    put:
      tags:
        - "Subscription Policy (Individual)"
      summary: "Update a Subscription Policy"
      description: "Updates an existing subscription-level throttling policy.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:tier_manage"
    delete:
      tags:
        - "Subscription Policy (Individual)"
      summary: "Delete a Subscription Policy"
      description: "This operation can be used to delete a subscription-level throttling\
        \ policy specifying the Id of the policy as a path paramter.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:tier_manage"
  /throttling/policies/custom:
    get:
      tags:
        - "Custom Rules (Collection)"
      summary: "Get all Custom Rules"
      description: "Retrieves all Custom Rules.\n\n**NOTE:**\n* Only super tenant\
        \ users are allowed for this operation.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:tier_view"
      x-wso2-curl: "curl -k -H \"Authorization: Bearer 0d63e133-7ad6-3aeb-9ca9-9299e0708122\"\
        \ https://localhost:9443/api/am/admin/v1/throttling/policies/custom"
      x-wso2-request: "GET https://localhost:9443/api/am/admin/v1/throttling/policies/custom\n\
        Authorization: Bearer 0d63e133-7ad6-3aeb-9ca9-9299e0708122\n"
      x-wso2-response: "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n\
        {\r\n  \"count\": 1,\r\n  \"list\": [\r\n    {\r\n      \"policyId\": \"33662a62-8db1-4d75-af08-afd63c6bd0b4\"\
        ,\r\n      \"policyName\": \"custom1\",\r\n      \"displayName\": null,\r\n\
        \      \"description\": \"Allow 10 requests per minute for admin user\",\r\
        \n      \"isDeployed\": true,\r\n      \"siddhiQuery\": \"FROM RequestStream\\\
        nSELECT userId, ( userId == 'admin@carbon.super' ) AS isEligible , str:concat('admin@carbon.super','')\
        \ as throttleKey\\nINSERT INTO EligibilityStream; \\n\\nFROM EligibilityStream[isEligible==true]#throttler:timeBatch(1\
        \ min) \\nSELECT throttleKey, (count(userId) >= 10) as isThrottled, expiryTimeStamp\
        \ group by throttleKey \\nINSERT ALL EVENTS into ResultStream;\",\r\n    \
        \  \"keyTemplate\": \"$userId\"\r\n    }\r\n  ]\r\n}"
    post:
      tags:
        - "Custom Rules (Collection)"
      summary: "Add a Custom Rule"
      description: "Adds a new Custom Rule.\n\n**NOTE:**\n* Only super tenant users\
        \ are allowed for this operation.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:tier_manage"
      x-wso2-curl: "curl -k -X POST -H \"Authorization: Bearer 0d63e133-7ad6-3aeb-9ca9-9299e0708122\"\
        \ -H \"Content-Type: application/json\" https://localhost:9443/api/am/admin/v1/throttling/policies/custom\
        \ -d @data.json"
      x-wso2-request: "POST https://localhost:9443/api/am/admin/v1/throttling/policies/custom\r\
        \nAuthorization: Bearer 0d63e133-7ad6-3aeb-9ca9-9299e0708122\r\nContent-Type:\
        \ application/json\r\n\r\n{\r\n  \"policyName\": \"custom1\",\r\n  \"description\"\
        : \"Allow 10 requests per minute for admin user\",\r\n  \"siddhiQuery\": \"\
        FROM RequestStream\\nSELECT userId, ( userId == 'admin@carbon.super' ) AS\
        \ isEligible , str:concat('admin@carbon.super','') as throttleKey\\nINSERT\
        \ INTO EligibilityStream; \\n\\nFROM EligibilityStream[isEligible==true]#throttler:timeBatch(1\
        \ min) \\nSELECT throttleKey, (count(userId) >= 10) as isThrottled, expiryTimeStamp\
        \ group by throttleKey \\nINSERT ALL EVENTS into ResultStream;\",\r\n  \"\
        keyTemplate\": \"$userId\"\r\n}"
      x-wso2-response: "HTTP/1.1 201 Created\r\nLocation: https://localhost:9443/api/am/admin/v1/throttling/policies/custom/22c71b7d-7013-4b80-bf7a-e86b471fb575\r\
        \nContent-Type: application/json\r\n\r\n{\r\n  \"policyId\": \"22c71b7d-7013-4b80-bf7a-e86b471fb575\"\
        ,\r\n  \"policyName\": \"custom1\",\r\n  \"displayName\": null,\r\n  \"description\"\
        : \"Allow 10 requests per minute for admin user\",\r\n  \"isDeployed\": true,\r\
        \n  \"siddhiQuery\": \"FROM RequestStream\\nSELECT userId, ( userId == 'admin@carbon.super'\
        \ ) AS isEligible , str:concat('admin@carbon.super','') as throttleKey\\nINSERT\
        \ INTO EligibilityStream; \\n\\nFROM EligibilityStream[isEligible==true]#throttler:timeBatch(1\
        \ min) \\nSELECT throttleKey, (count(userId) >= 10) as isThrottled, expiryTimeStamp\
        \ group by throttleKey \\nINSERT ALL EVENTS into ResultStream;\",\r\n  \"\
        keyTemplate\": \"$userId\"\r\n}"
  /throttling/policies/custom/{ruleId}:
    get:
      tags:
        - "Custom Rules (Individual)"
      summary: "Get a Custom Rule"
      description: "Retrieves a Custom Rule. We need to provide the policy Id as a\
        \ path parameter.\n\n**NOTE:**\n* Only super tenant users are allowed for\
        \ this operation.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:tier_view"
      x-wso2-curl: "curl -k -H \"Authorization: Bearer 0d63e133-7ad6-3aeb-9ca9-9299e0708122\"\
        \ https://localhost:9443/api/am/admin/v1/throttling/policies/custom/33662a62-8db1-4d75-af08-afd63c6bd0b4"
      x-wso2-request: "GET https://localhost:9443/api/am/admin/v1/throttling/policies/custom/33662a62-8db1-4d75-af08-afd63c6bd0b4\n\
        Authorization: Bearer 0d63e133-7ad6-3aeb-9ca9-9299e0708122\n"
      x-wso2-response: "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n\
        {\r\n  \"policyId\": \"33662a62-8db1-4d75-af08-afd63c6bd0b4\",\r\n  \"policyName\"\
        : \"custom1\",\r\n  \"displayName\": null,\r\n  \"description\": \"Allow 10\
        \ requests per minute for admin user\",\r\n  \"isDeployed\": true,\r\n  \"\
        siddhiQuery\": \"FROM RequestStream\\nSELECT userId, ( userId == 'admin@carbon.super'\
        \ ) AS isEligible , str:concat('admin@carbon.super','') as throttleKey\\nINSERT\
        \ INTO EligibilityStream; \\n\\nFROM EligibilityStream[isEligible==true]#throttler:timeBatch(1\
        \ min) \\nSELECT throttleKey, (count(userId) >= 10) as isThrottled, expiryTimeStamp\
        \ group by throttleKey \\nINSERT ALL EVENTS into ResultStream;\",\r\n  \"\
        keyTemplate\": \"$userId\"\r\n}"
    put:
      tags:
        - "Custom Rules (Individual)"
      summary: "Update a Custom Rule"
      description: "Updates an existing Custom Rule.\n\n**NOTE:**\n* Only super tenant\
        \ users are allowed for this operation.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:tier_manage"
      x-wso2-curl: "curl -k -X PUT -H \"Authorization: Bearer 0d63e133-7ad6-3aeb-9ca9-9299e0708122\"\
        \ -H \"Content-Type: application/json\" https://localhost:9443/api/am/admin/v1/throttling/policies/custom/33662a62-8db1-4d75-af08-afd63c6bd0b4\
        \ -d @data.json"
      x-wso2-request: "PUT https://localhost:9443/api/am/admin/v1/throttling/policies/custom/33662a62-8db1-4d75-af08-afd63c6bd0b4\r\
        \nAuthorization: Bearer 0d63e133-7ad6-3aeb-9ca9-9299e0708122\r\nContent-Type:\
        \ application/json\r\n\r\n{\r\n  \"policyName\": \"custom1\",\r\n  \"description\"\
        : \"Allow 10 requests per minute for admin user\",\r\n  \"siddhiQuery\": \"\
        FROM RequestStream\\nSELECT userId, ( userId == 'admin@carbon.super' ) AS\
        \ isEligible , str:concat('admin@carbon.super','') as throttleKey\\nINSERT\
        \ INTO EligibilityStream; \\n\\nFROM EligibilityStream[isEligible==true]#throttler:timeBatch(1\
        \ min) \\nSELECT throttleKey, (count(userId) >= 10) as isThrottled, expiryTimeStamp\
        \ group by throttleKey \\nINSERT ALL EVENTS into ResultStream;\",\r\n  \"\
        keyTemplate\": \"$userId\"\r\n}"
      x-wso2-response: "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n\
        {\r\n  \"policyId\": \"33662a62-8db1-4d75-af08-afd63c6bd0b4\",\r\n  \"policyName\"\
        : \"custom1\",\r\n  \"displayName\": null,\r\n  \"description\": \"Allow 10\
        \ requests per minute for admin user\",\r\n  \"isDeployed\": true,\r\n  \"\
        siddhiQuery\": \"FROM RequestStream\\nSELECT userId, ( userId == 'admin@carbon.super'\
        \ ) AS isEligible , str:concat('admin@carbon.super','') as throttleKey\\nINSERT\
        \ INTO EligibilityStream; \\n\\nFROM EligibilityStream[isEligible==true]#throttler:timeBatch(1\
        \ min) \\nSELECT throttleKey, (count(userId) >= 10) as isThrottled, expiryTimeStamp\
        \ group by throttleKey \\nINSERT ALL EVENTS into ResultStream;\",\r\n  \"\
        keyTemplate\": \"$userId\"\r\n}"
    delete:
      tags:
        - "Custom Rules (Individual)"
      summary: "Delete a Custom Rule"
      description: "Delete a Custom Rule. We need to provide the Id of the policy\
        \ as a path parameter.\n\n**NOTE:**\n* Only super tenant users are allowed\
        \ for this operation.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:tier_manage"
      x-wso2-curl: "curl -k -X DELETE -H \"Authorization: Bearer 0d63e133-7ad6-3aeb-9ca9-9299e0708122\"\
        \ https://localhost:9443/api/am/admin/v1/throttling/policies/custom/33662a62-8db1-4d75-af08-afd63c6bd0b4"
      x-wso2-request: "DELETE https://localhost:9443/api/am/admin/v1/throttling/policies/custom/33662a62-8db1-4d75-af08-afd63c6bd0b4\n\
        Authorization: Bearer 0d63e133-7ad6-3aeb-9ca9-9299e0708122\n"
      x-wso2-response: "HTTP/1.1 200 OK"
  /throttling/policies/advanced:
    get:
      tags:
        - "Advanced Policy (Collection)"
      summary: "Get all Advanced throttling policies."
      description: "Retrieves all existing Advanced level throttling policies.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:tier_view"
    post:
      tags:
        - "Advanced Policy (Collection)"
      summary: "Add an Advanced Throttling Policy"
      description: "Add a new Advanced level throttling policy.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:tier_manage"
  /throttling/policies/advanced/{policyId}:
    get:
      tags:
        - "Advanced Policy (Individual)"
      summary: "Get an Advanced Policy"
      description: "Retrieves an Advanced Policy.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:tier_view"
    put:
      tags:
        - "Advanced Policy (Individual)"
      summary: "Update an Advanced Throttling Policy"
      description: "Updates an existing Advanced level throttling policy.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:tier_manage"
    delete:
      tags:
        - "Advanced Policy (Individual)"
      summary: "Delete an Advanced Throttling Policy"
      description: "Deletes an Advanced level throttling policy.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:tier_manage"
  /throttling/blacklist:
    get:
      tags:
        - "Blacklist (Collection)"
      summary: "Get all blocking condtions"
      description: "Retrieves all existing blocking condtions.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:bl_view"
      x-wso2-curl: "curl -k -H \"Authorization: Bearer a1e3951b-a15c-3d79-a15b-99f1d612843e\"\
        \ https://localhost:9443/api/am/admin/v1/throttling/blacklist"
      x-wso2-request: "GET https://localhost:9443/api/am/admin/v1/throttling/blacklist\n\
        Authorization: Bearer a1e3951b-a15c-3d79-a15b-99f1d612843e\n"
      x-wso2-response: "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n\
        {\r\n  \"count\": 3,\r\n  \"list\": [\r\n    {\r\n      \"conditionId\": \"\
        0b65b686-841b-48eb-b4c2-427d24584d71\",\r\n      \"conditionType\": \"IP\"\
        ,\r\n      \"conditionValue\": \"127.0.0.332\",\r\n      \"conditionStatus\"\
        : \"true\"\r\n    },\r\n    {\r\n      \"conditionId\": \"3baa990c-f90b-4e3e-9db7-f29ee7f46f48\"\
        ,\r\n      \"conditionType\": \"IP\",\r\n      \"conditionValue\": \"localhost\"\
        ,\r\n      \"conditionStatus\": \"false\"\r\n    },\r\n    {\r\n      \"conditionId\"\
        : \"b513eb68-69e8-4c32-92cf-852c101363cf\",\r\n      \"conditionType\": \"\
        IP\",\r\n      \"conditionValue\": \"10.100.7.77\",\r\n      \"conditionStatus\"\
        : \"true\"\r\n    }\r\n  ]\r\n}"
    post:
      tags:
        - "Blacklist (Collection)"
      summary: "Add a Blocking condition"
      description: "Adds a new Blocking condition.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:bl_manage"
      x-wso2-curl: "curl -k -X POST -H \"Authorization: Bearer a1e3951b-a15c-3d79-a15b-99f1d612843e\"\
        \ -H \"Content-Type: application/json\" https://localhost:9443/api/am/admin/v1/throttling/blacklist"
      x-wso2-request: "POST https://localhost:9443/api/am/admin/v1/throttling/blacklist\r\
        \nAuthorization: Bearer a1e3951b-a15c-3d79-a15b-99f1d612843e\r\nContent-Type:\
        \ application/json\r\n\r\n{\r\n   \"conditionType\": \"IP\",\r\n   \"conditionValue\"\
        : \"10.100.7.77\",\r\n      \"conditionStatus\": \"false\"\r\n    }\r\n"
      x-wso2-response: "HTTP/1.1 201 Created\r\nLocation: https://localhost:9443/api/am/admin/v1/throttling/blacklist/b513eb68-69e8-4c32-92cf-852c101363cf\r\
        \nContent-Type: application/json\r\n\r\n{\r\n  \"conditionId\": \"b513eb68-69e8-4c32-92cf-852c101363cf\"\
        ,\r\n  \"conditionType\": \"IP\",\r\n  \"conditionValue\": \"10.100.7.77\"\
        ,\r\n      \"conditionStatus\": \"false\"\r\n    }"
  /throttling/blacklist/{conditionId}:
    get:
      tags:
        - "Blacklist (Individual)"
      summary: "Get a Blocking Condition"
      description: "Retrieves a Blocking Condition providing the condition Id\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:bl_view"
      x-wso2-curl: "curl -k -H \"Authorization: Bearer a1e3951b-a15c-3d79-a15b-99f1d612843e\"\
        \ https://localhost:9443/api/am/admin/v1/throttling/blacklist/b513eb68-69e8-4c32-92cf-852c101363c"
      x-wso2-request: "GET https://localhost:9443/api/am/admin/v1/throttling/blacklist/b513eb68-69e8-4c32-92cf-852c101363c\n\
        Authorization: Bearer a1e3951b-a15c-3d79-a15b-99f1d612843e\n"
      x-wso2-response: "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n\
        {\r\n  \"conditionId\": \"b513eb68-69e8-4c32-92cf-852c101363cf\",\r\n  \"\
        conditionType\": \"IP\",\r\n  \"conditionValue\": \"10.100.7.77\"\r\n}"
    delete:
      tags:
        - "Blacklist (Individual)"
      summary: "Delete a Blocking condition"
      description: "Deletes an existing Blocking condition\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:bl_manage"
      x-wso2-curl: "curl -k -X DELETE -H \"Authorization: Bearer a1e3951b-a15c-3d79-a15b-99f1d612843e\"\
        \ -H \"Content-Type: application/json\" https://localhost:9443/api/am/admin/v1/throttling/blacklist/b513eb68-69e8-4c32-92cf-852c101363cf"
      x-wso2-request: "DELETE https://localhost:9443/api/am/admin/v1/throttling/blacklist/b513eb68-69e8-4c32-92cf-852c101363cf\n\
        Authorization: Bearer a1e3951b-a15c-3d79-a15b-99f1d612843e\n"
      x-wso2-response: "HTTP/1.1 200 OK"
    patch:
      tags:
        - "Blacklist (Individual)"
      summary: "Update a blocking condition"
      description: "Update a blocking condition by Id\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:bl_manage"
      x-wso2-curl: "curl -k -X PATCH -H \"Authorization: Bearer 0d63e133-7ad6-3aeb-9ca9-9299e0708122\"\
        \ -H \"Content-Type: application/json\" https://localhost:9443/api/am/admin/v1/throttling/blacklist/b513eb68-69e8-4c32-92cf-852c101363cf\
        \ -d @data.json"
      x-wso2-request: "PUT https://localhost:9443/api/am/admin/v1/throttling/blacklist/b513eb68-69e8-4c32-92cf-852c101363cf\r\
        \nAuthorization: Bearer a1e3951b-a15c-3d79-a15b-99f1d612843e\r\nContent-Type:\
        \ application/json\r\n\r\n{\r\n    \"conditionStatus\": \"true\"\r\n    }\r\
        \n"
      x-wso2-response: "HTTP/1.1 200 Ok\r\nContent-Type: application/json\r\n\r\n\
        {\r\n  \"conditionId\": \"b513eb68-69e8-4c32-92cf-852c101363cf\",\r\n  \"\
        conditionType\": \"IP\",\r\n  \"conditionValue\": \"10.100.7.77\",\r\n   \
        \   \"conditionStatus\": \"true\"\r\n    }"
  /applications:
    get:
      tags:
        - "Application (Collection)"
      summary: "Retrieve/Search applications\n"
      description: "This operation can be used to retrieve list of applications that\
        \ is belonged to the given user, If no user\nis provided then the application\
        \ for the user associated with the provided access token will be returned.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:app_owner_change"
            - "apim:app_import_export"
      x-wso2-request: "GET https://localhost:9443/api/am/admin/v1/applications\nAuthorization:\
        \ Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n"
      x-wso2-curl: "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\"\
        \ \"https://localhost:9443/api/am/admin/v1/applications\""
      x-wso2-response: "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\n   \"\
        previous\": \"\",\n   \"list\":    [\n            {\n         \"groupId\"\
        : \"\",\n         \"owner\": \"admin\",\n           \"applicationId\": \"\
        367a2361-8db5-4140-8133-c6c8dc7fa0c4\",\n         \"status\": \"APPROVED\"\
        ,\n         \"name\": \"app1\"\n      },\n            {\n         \"groupId\"\
        : \"\",\n         \"owner\": \"admin\",\n             \"applicationId\": \"\
        896658a0-b4ee-4535-bbfa-806c894a4015\",\n          \"status\": \"APPROVED\"\
        ,\n         \"name\": \"DefaultApplication\"\n      }\n   ],\n   \"count\"\
        : 2,\n   \"next\": \"\"\n}"
  /applications/{applicationId}:
    delete:
      tags:
        - "Applications"
      summary: "Remove an application\n"
      description: "This operation can be used to remove an application specifying\
        \ its id.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:app_import_export"
  /applications/{applicationId}/change-owner:
    post:
      tags:
        - "Application"
      summary: "Change Application Owner"
      description: "This operation is used to change the owner of an Application.\n\
        In order to change the owner of an application, we need to pass the new application\
        \ owner as a query parameter\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:app_owner_change"
      x-wso2-curl: "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\"\
        \ -X POST \"https://localhost:9443/api/am/admin/v1/applications/890a4f4d-09eb-4877-a323-57f6ce2ed79b/change-owner?owner=admin\""
      x-wso2-request: "POST https://localhost:9443/api/am/admin/v1/apis/change-owner?apiId=890a4f4d-09eb-4877-a323-57f6ce2ed79b&action=Publish\n\
        Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n"
      x-wso2-response: "HTTP/1.1 200 OK"
  /export/applications:
    get:
      tags:
        - "Application (Individual)"
      summary: "Export an Application"
      description: "This operation can be used to export the details of a particular\
        \ Application as a zip file.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:app_import_export"
      x-wso2-curl: "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\"\
        \ -X GET https://localhost:9443/api/am/admin/v1/export/applications?appName=sampleApp&appOwner=admin\
        \ > admin_sampleApp.zip"
      x-wso2-request: "GET https://localhost:9443/api/am/admin/v1/export/applications?appName=sampleApp&appOwner=admin\n\
        Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n"
      x-wso2-response: "HTTP/1.1 200 OK\n Connection: keep-alive\n  Content-Disposition:\
        \ attachment; filename=\"exported-application.zip\"\n  Content-Type: application/zip"
  /import/applications:
    post:
      tags:
        - "Application (Individual)"
      summary: "Import an Application"
      description: "This operation can be used to import an Application.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:app_import_export"
      x-wso2-curl: "curl -k -F \"file=@exported.zip\" -X POST -H \"Authorization:\
        \ Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://localhost:9443/api/am/admin/v1/import/applications"
      x-wso2-request: "POST https://localhost:9443/api/am/admin/v1/import/applications\n\
        Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n"
      x-wso2-response: "HTTP/1.1 201 Created\nLocation: https://localhost:9443/api/am/admin/v1/applications/c30f3a6e-ffa4-4ae7-afce-224d1f820524\n\
        Content-Type: application/json\n\n{\n   \"groupId\": \"\",\n   \"callbackUrl\"\
        : \"http://my.server.com/callback\",\n   \"owner\": \"admin\",\n   \"applicationId\"\
        : \"c30f3a6e-ffa4-4ae7-afce-224d1f820524\",\n   \"status\": \"APPROVED\",\n\
        \   \"name\": \"sampleapp\" \n}"
  /import/api:
    post:
      tags:
        - "API (Individual)"
      summary: "Import an API"
      description: "This operation can be used to import an API.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:api_import_export"
      x-wso2-curl: "curl -k -F \"file=@exported.zip\" -X POST -H \"Authorization:\
        \ Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://localhost:9443/api/am/admin/v1/import/api?preserveProvider=false&overwrite=false"
      x-wso2-request: "POST https://localhost:9443/api/am/admin/v1/import/apis\nAuthorization:\
        \ Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n"
      x-wso2-response: "HTTP/1.1 200 OK\nAPI imported successfully."
  /export/api:
    get:
      tags:
        - "API (Individual)"
      summary: "Export an API"
      description: "This operation can be used to export the details of a particular\
        \ API as a zip file.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:api_import_export"
      x-wso2-curl: "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\"\
        \ -X GET https://localhost:9443/api/am/admin/v1/export/api?name=PizzaShackAPI&version=1.0.0&providerName=admin\
        \ > exportAPI.zip"
      x-wso2-request: "GET https://localhost:9443/api/am/admin/v1/export/api?name=SampleAPI&version=1.0.0&providerName=admin\n\
        Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n"
      x-wso2-response: "HTTP/1.1 200 OK\n Connection: keep-alive\n  Content-Disposition:\
        \ attachment; filename=\"exported-api.zip\"\n  Content-Type: application/zip"
  /import/api-product:
    post:
      tags:
        - "API Product (Individual)"
      summary: "Import an API Product"
      description: "This operation can be used to import an API Product.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:api_product_import_export"
      x-wso2-curl: "curl -k -F \"file=@exported.zip\" -X POST -H \"Authorization:\
        \ Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://localhost:9443/api/am/admin/v1/import/api-product?preserveProvider=false&overwriteAPIs=false&overwriteAPIProduct=false"
      x-wso2-request: "POST https://localhost:9443/api/am/admin/v1/import/api-product\n\
        Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n"
      x-wso2-response: "HTTP/1.1 200 OK\nAPI Product imported successfully."
  /export/api-product:
    get:
      tags:
        - "API Product (Individual)"
      summary: "Export an API Product"
      description: "This operation can be used to export the details of a particular\
        \ API Product as a zip file.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:api_product_import_export"
      x-wso2-curl: "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\"\
        \ -X GET https://localhost:9443/api/am/admin/v0.17/export/api-product?name=SampleAPIProduct&version=1.0.0&providerName=admin\
        \ > exportAPIProduct.zip"
      x-wso2-request: "GET https://localhost:9443/api/am/admin/v0.17/export/api-product?name=SampleAPIProduct&version=1.0.0&providerName=admin\n\
        Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n"
      x-wso2-response: "HTTP/1.1 200 OK\n Connection: keep-alive\n  Content-Disposition:\
        \ attachment; filename=\"exported-api-product.zip\"\n  Content-Type: application/zip"
  /labels:
    get:
      tags:
        - "Label Collection"
      summary: "Get all registered Labels"
      description: "Get all registered Labels\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:label_read"
      x-wso2-request: "GET https://localhost:9443/api/am/admin/v1/labels\nAuthorization:\
        \ Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n"
      x-wso2-curl: "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\"\
        \ \"https://localhost:9443/api/am/admin/v1/labels\""
      x-wso2-response: "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n\
        {\r\n  \"count\": 1,\r\n  \"list\": [\r\n\t{\r\n\t\"id\":\"d7cf8523-9180-4255-84fa-6cb171c1f779\"\
        ,\r\n\t\"name\":\"internal\",\r\n\t\"description\":\"label used for internal\
        \ purpose\",\r\n\t\"accessUrls\":[\r\n\t  \"https://localhost:9095\"\r\n \
        \        ]\r\n       }\r\n   ]\r\n}"
    post:
      tags:
        - "Label"
      summary: "Add a Label"
      description: "Add a new gateway Label\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:label_manage"
      x-wso2-curl: "curl -k -X POST -H \"Authorization: Bearer 0d63e133-7ad6-3aeb-9ca9-9299e0708122\"\
        \ -H \"Content-Type: application/json\" https://apis.wso2.com/api/am/admin/v1/labels\
        \ -d @data.json"
      x-wso2-request: "POST https://localhost:9443/api/am/admin/v1/labels\r\nAuthorization:\
        \ Bearer 0d63e133-7ad6-3aeb-9ca9-9299e0708122\r\nContent-Type: application/json\r\
        \n\r\n   {\r\n       \"name\":\"internal\",\r\n\t\"description\":\"label used\
        \ for internal purpose\",\r\n\t\"accessUrls\":[\r\n\t  \"https://localhost:9095\"\
        \r\n         ]\r\n     }"
      x-wso2-response: "HTTP/1.1 201 Created\r\nContent-Type: application/json\r\n\
        \r\n{\r\n\t\"id\":\"d7cf8523-9180-4255-84fa-6cb171c1f779\",\r\n\t\"name\"\
        :\"internal\",\r\n\t\"description\":\"label used for internal purpose\",\r\
        \n\t\"accessUrls\":[\r\n\t  \"https://localhost:9095\"\r\n         ]\r\n \
        \      }\r\n   ]\r\n}"
  /bot-detection-data:
    get:
      summary: "Get all bot detected data\n"
      description: "Get all bot detected data\n"
      operationId: "getBotDetectionData"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:bot_data"
  /labels/{labelId}:
    put:
      tags:
        - "Label"
      summary: "Update a Label"
      description: "Update a Label by label Id\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:label_manage"
      x-wso2-curl: "curl -k -X PUT -H \"Authorization: Bearer 0d63e133-7ad6-3aeb-9ca9-9299e0708122\"\
        \ -H \"Content-Type: application/json\" https://localhost:9443/api/am/admin/v1/labels/d7cf8523-9180-4255-84fa-6cb171c1f779\
        \ -d @data.json"
      x-wso2-request: "PUT https://localhost:9443/api/am/admin/v1/labels/d7cf8523-9180-4255-84fa-6cb171c1f779\r\
        \nAuthorization: Bearer 0d63e133-7ad6-3aeb-9ca9-9299e0708122\r\nContent-Type:\
        \ application/json\r\n\r\n   {\r\n       \"name\":\"update_internal\",\r\n\
        \t\"description\":\"Updated label used for internal purpose\",\r\n\t\"accessUrls\"\
        :[\r\n\t  \"https://localhost:9095\"\r\n         ]\r\n     }"
      x-wso2-response: "HTTP/1.1 200 Ok\r\nContent-Type: application/json\r\n\r\n\
        {\r\n\t\"id\":\"d7cf8523-9180-4255-84fa-6cb171c1f779\",\r\n\t\"name\":\"updated_internal\"\
        ,\r\n\t\"description\":\"Updated label used for internal purpose\",\r\n\t\"\
        accessUrls\":[\r\n\t  \"https://localhost:9095\"\r\n         ]\r\n       }\r\
        \n   ]\r\n}"
    delete:
      tags:
        - "Label"
      summary: "Delete a Label"
      description: "Delete a Label by label Id\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:label_manage"
      x-wso2-response: "HTTP/1.1 200 OK"
  /monetization/publish-usage:
    post:
      tags:
        - "Monetization (Collection)"
      summary: "Publish Usage Records"
      description: "Publish Usage Records of Monetized APIs\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:monetization_usage_publish"
      x-wso2-curl: "curl -k -H \"Authorization: Bearer 0c6439fd-9b16-3c2e-be6e-1086e0b9aa93\"\
        \ -X POST -H \"Content-Type: application/json\" https://localhost:9443/api/am/admin/v1/monetization/publish-usage"
      x-wso2-request: "POST https://localhost:9443/api/am/admin/v1/monetization/publish-usage\r\
        \nAuthorization: Bearer 0c6439fd-9b16-3c2e-be6e-1086e0b9aa93\r\nContent-Type:\
        \ application/json"
      x-wso2-response: "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n\
        {\r\n\"status\":\"successfull\",\r\n\"message\":\"Records published successfully\"\
        \r\n}"
  /monetization/publish-usage/status:
    get:
      tags:
        - "Monetization (Collection)"
      summary: "Get the status of Monetization usage publisher"
      description: "Get the status of Monetization usage publisher\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:monetization_usage_publish"
      x-wso2-request: "GET https://localhost:9443/api/am/admin/v1/monetization/publish-usage/status\n\
        Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n"
      x-wso2-curl: "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\"\
        \ \"https://localhost:9443/api/am/admin/v1/monetization/publish-usage/status\""
      x-wso2-response: "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n\
        {\r\n  \"state\": \"RUNNING\",\r\n ,\"status\":\"SUCCESSFULL\",\r\n, \"started\
        \ time\":\"12345678056L\",\r\n, \"last published time\":\"12345678056L\",\r\
        \n}"
  /workflows:
    get:
      tags:
        - "Workflow (Collection)"
      summary: "Retrieve All pending workflow processes\n"
      description: "This operation can be used to retrieve list of workflow pending\
        \ processes.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:api_workflow_view"
      x-wso2-request: "GET https://localhost:9443/api/am/admin/v1/workflows\nAuthorization:\
        \ Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n"
      x-wso2-curl: "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\"\
        \ \"https://localhost:9443/api/am/admin/v1/workflows\""
      x-wso2-response: "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\n   \"\
        previous\": \"\",\n   \"list\":    [\n            {\n    \"WF_TYPE\": \"AM_APPLICATION_CREATION\"\
        ,\n         \"WF_STATUS\": \"APPROVED\",\n         \"WF_CREATED_TIME\": \"\
        \  2020-02-10 09:33:34.476\"\n    \"WF_UPDATED_TIME\": \"  2020-02-10 09:33:34.476\"\
        \n    \"WF_STATUS_DESC\": \"  Approve workflow request\"\n   \"TENANT_ID\"\
        : \"-1234\",\n  \"TENANT_DOMAIN\": \"carbon.super\",\n  \"WF_EXTERNAL_REFERENCE\"\
        : \"5871244b-d6f3-466e-8995-8accd1e64303\",\n  \"PAYLOAD\": \"7b2263616c6c4261636b55524c22\"\
        ,\n },\n  {\n         \"WF_ID\": \"\",\n         \"WF_REFERENCE\": \"ABBA\"\
        ,\n           \"WF_TYPE\": \"AM_APPLICATION_CREATION\",\n         \"WF_STATUS\"\
        : \"APPROVED\",\n         \"WF_CREATED_TIME\": \"  2020-01-10 09:32:34.476\"\
        \n    \"WF_UPDATED_TIME\": \"  2020-03-12 09:34:34.476\"\n    \"WF_STATUS_DESC\"\
        : \"  Approve workflow request\"\n   \"TENANT_ID\": \"-1234\",\n  \"TENANT_DOMAIN\"\
        : \"carbon.super\",\n  \"WF_EXTERNAL_REFERENCE\": \"5871244b-d6f3-466e-8922-8accd1e64303\"\
        ,\n  \"PAYLOAD\": \"7b226170694e616d65223a2253616\",\n }          "
  /workflows/{externalWorkflowRef}:
    get:
      tags:
        - "Workflows (Individual)"
      summary: "Get details of a the pending workflow request according to the External\
        \ Workflow Reference.\n"
      description: "Using this operation, you can retrieve complete details of a pending\
        \ workflow request that either belongs to application creation, application\
        \ subscription, application registration, api state change, user self sign\
        \ up.. You need to provide the External_Workflow_Reference of the workflow\
        \ Request to retrive it.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:api_workflow_view"
      x-wso2-curl: "curl https://localhost:9443/api/am/admin/v1/workflows/c43a325c-260b-4302-81cb-768eafaa3aed"
      x-wso2-curl-tenant: "curl -k -H \"X-WSO2-Tenant:test.com\" https://localhost:9443/api/am/admin/v0.17/workflows/c43a325c-260b-4302-81cb-768eafaa3aed"
      x-wso2-request: "GET https://localhost:9443/api/am/admin/v1/workflows/c43a325c-260b-4302-81cb-768eafaa3aed\n"
      x-wso2-response: "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\n   \"\
        previous\": \"\",\n   \"list\":    [\n            {\n                 \"WF_TYPE\"\
        : \"AM_APPLICATION_CREATION\",\n         \"WF_STATUS\": \"APPROVED\",\n  \
        \       \"WF_CREATED_TIME\": \"  2020-02-10 09:33:34.476\"\n    \"WF_UPDATED_TIME\"\
        : \"  2020-02-10 09:33:34.476\"\n    \"WF_STATUS_DESC\": \"  Approve workflow\
        \ request\"\n   \"TENANT_ID\": \"-1234\",\n  \"TENANT_DOMAIN\": \"carbon.super\"\
        ,\n  \"WF_EXTERNAL_REFERENCE\": \"5871244b-d6f3-466e-8995-8accd1e64303\",\n\
        \  \"PAYLOAD\": \"7b2263616c6c4261636b55524c22\",\n } "
  /workflows/update-workflow-status:
    post:
      tags:
        - "Workflows (Individual)"
      summary: "Update workflow status"
      description: "This operation can be used to approve or reject a workflow task.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:api_workflow_approve"
      x-wso2-curl: "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\"\
        \ -H \"Content-Type: application/json\" -X POST -d @data.json \"https://localhost:9443/api/am/publisher/v1/workflows/update-workflow-status?workflowReferenceId=56e3a170-a7a7-45f8-b051-7e43a58a67e1\""
      x-wso2-request: "POST https://localhost:9443/api/am/publisher/v1/workflows/update-workflow-status?workflowReferenceId=56e3a170-a7a7-45f8-b051-7e43a58a67e1\n\
        Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\nContent-Type:\
        \ application/json\n\n{\n   \"status\" : \"APPROVED\",\n   \"attributes\"\
        \ : {\n      \"apiCurrentState\": \"Created\",\n      \"apiLCAction\": \"\
        Publish\",\n      \"apiName\":\"APIname\",\n      \"apiVersion\" : \"1.0.0\"\
        ,\n      \"apiProvider\" : \"admin\",\n      \"invoker\": \"admin\"\n   }\n\
        }"
      x-wso2-response: "HTTP/1.1 200 OK"
  /tenant-info/{username}:
    get:
      tags:
        - "Tenants"
      summary: "Get tenant id of the user\n"
      description: "This operation is to get tenant id of the provided user\n"
      operationId: "getTenantInfoByUsername"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:tenantInfo"
      x-wso2-curl: "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\"\
        \ -H \"Content-Type: application/json\" -X GET \"https://localhost:9443/api/am/admin/v1/tenant-info/john/info\""
      x-wso2-request: "GET https://localhost:9443/api/am/admin/v1/tenant-info/john\n\
        Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\nContent-Type:\
        \ application/json\n\n{\n   \"tenantDomain\" : \"carbon.super\",\n   \"tenantId\"\
        \ : -1234 \n}"
      x-wso2-response: "HTTP/1.1 200 OK"
  /custom-urls/{tenantDomain}:
    get:
      tags:
        - "Tenants"
      summary: "Get custom-url info of a tenant domain\n"
      description: "This operation is to get custom-url information of the provided\
        \ tenant-domain\n"
      operationId: "getCustomUrlInfoByTenantDomain"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:tenantInfo"
      x-wso2-curl: "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\"\
        \ -H \"Content-Type: application/json\" -X GET \"https://localhost:9443/api/am/admin/v1/custom-url/foo.com\""
      x-wso2-request: "GET https://localhost:9443/api/am/admin/v1/custom-url/foo.com\n\
        Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\nContent-Type:\
        \ application/json\n\n{\n   \"tenantDomain\" : \"foo.com\",\n}"
      x-wso2-response: "HTTP/1.1 200 OK"
  /api-categories:
    get:
      tags:
        - "API Category (Collection)"
      summary: "Get all API categories"
      description: "Get all API categories\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:admin_operations"
      x-wso2-request: "GET https://localhost:9443/api/am/admin/v1/api-categories\n\
        Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n"
      x-wso2-curl: "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\"\
        \ \"https://localhost:9443/api/am/admin/v1/api-categories\""
      x-wso2-response: "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n\
        {\r\n   \"count\":1,\r\n   \"list\":[\r\n      {\r\n         \"id\":\"463e2c9f-5e99-43c3-a66e-de7e0f367373\"\
        ,\r\n         \"name\":\"Finance\",\r\n         \"description\":\"Finance\
        \ related APIS\"\r\n      \"numberOfAPIs\":1\r\n}\r\n   ]\r\n      }\r\n \
        \  ]\r\n}"
    post:
      tags:
        - "API Category (Individual)"
      summary: "Add a new API Category"
      description: "Add a new API Category\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:admin_operations"
      x-wso2-curl: "curl -k -X POST -H \"Authorization: Bearer 0d63e133-7ad6-3aeb-9ca9-9299e0708122\"\
        \ -H \"Content-Type: application/json\" https://apis.wso2.com/api/am/admin/v1/api-categories\
        \ -d @data.json"
      x-wso2-request: "POST https://localhost:9443/api/am/admin/v1/api-categories\r\
        \nAuthorization: Bearer 0d63e133-7ad6-3aeb-9ca9-9299e0708122\r\nContent-Type:\
        \ application/json\r\n\r\n -d  {\r\n         \"name\":\"Finance\",\r\n   \
        \      \"description\":\"Finance related APIS\"\r\n }"
      x-wso2-response: "HTTP/1.1 201 Created\r\nContent-Type: application/json\r\n\
        \r\n{\r\n   \"count\":1,\r\n   \"list\":[\r\n      {\r\n         \"id\":\"\
        463e2c9f-5e99-43c3-a66e-de7e0f367373\",\r\n         \"name\":\"Finance\",\r\
        \n         \"description\":\"Finance related APIS\"\r\n }"
  /api-categories/{apiCategoryId}:
    put:
      tags:
        - "API Category (Individual)"
      summary: "Update an API Category"
      description: "Update an API Category by category Id\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:admin_operations"
      x-wso2-curl: "curl -k -X PUT -H \"Authorization: Bearer 0d63e133-7ad6-3aeb-9ca9-9299e0708122\"\
        \ -H \"Content-Type: application/json\" https://localhost:9443/api/am/admin/v1/api-categories/d7cf8523-9180-4255-84fa-6cb171c1f779\
        \ -d @data.json"
      x-wso2-request: "PUT https://localhost:9443/api/am/admin/v1/api-categories/d7cf8523-9180-4255-84fa-6cb171c1f779\r\
        \nAuthorization: Bearer 0d63e133-7ad6-3aeb-9ca9-9299e0708122\r\nContent-Type:\
        \ application/json\r\n\r\n   {\r\n       \"name\":\"update_internal\",\r\n\
        \t\"description\":\"Updated label used for internal purpose\",\r\n\t\"accessUrls\"\
        :[\r\n\t  \"https://localhost:9095\"\r\n         ]\r\n     }"
      x-wso2-response: "HTTP/1.1 200 Ok\r\nContent-Type: application/json\r\n\r\n\
        {\r\n   \"count\":1,\r\n   \"list\":[\r\n      {\r\n         \"id\":\"463e2c9f-5e99-43c3-a66e-de7e0f367373\"\
        ,\r\n         \"name\":\"Finance\",\r\n         \"description\":\"Finance\
        \ related APIS\"\r\n      }\r\n   ]\r\n}"
    delete:
      tags:
        - "API Category (Individual)"
      summary: "Delete an API Category"
      description: "Delete an API Category by API Category Id\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:admin_operations"
      x-wso2-response: "HTTP/1.1 200 OK"
  /settings:
    get:
      tags:
        - "Settings"
      summary: "Retreive admin settings"
      description: "Retreive admin settings\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:admin_settings"
  /alert-types:
    get:
      tags:
        - "Alerts"
      summary: "Get the list of admin alert types.\n"
      description: "This operation is used to get the list of supportd alert types\
        \ for the apim admin dashboard\n"
      operationId: "getAdminAlertTypes"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:admin_alert_manage"
  /alert-subscriptions:
    get:
      tags:
        - "Alert Subscriptions"
      summary: "Get the list of API Admin alert types subscribed by the user.\n"
      description: "This operation is used to get the list of subscribed alert types\
        \ by the user.\n"
      operationId: "getSubscribedAlertTypes"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:admin_alert_manage"
    put:
      tags:
        - "Alert Subscriptions"
      summary: "Subscribe to an admin alert.\n"
      description: "This operation is used to subscribe to admin alerts\n"
      operationId: "subscribeToAlerts"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:admin_alert_manage"
    delete:
      tags:
        - "Alert Subscriptions"
      summary: "Unsubscribe user from all the admin alert types.\n"
      description: "This operation is used to unsubscribe the respective user from\
        \ all the admin alert types.\n"
      operationId: "unsubscribeAllAlerts"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:admin_alert_manage"
  /alert-subscriptions/bot-detection:
    get:
      tags:
        - "Bot Detection Alert Subscriptions"
      summary: "Get the list of subscriptions for bot detection\n"
      description: "Get the list of subscriptions which are subscribed to receive\
        \ email alerts for bot detection\n"
      operationId: "getBotDetectionAlertSubscriptions"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:admin_alert_manage"
    post:
      tags:
        - "Bot Detection Alert Subscriptions"
      summary: "Subscribe for bot detection alerts"
      description: "Register a subscription for bot detection alerts\n"
      operationId: "subscribeForBotDetectionAlerts"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:admin_alert_manage"
  /alert-subscriptions/bot-detection/{uuid}:
    delete:
      tags:
        - "Bot Detection Alert Subscriptions"
      summary: "Unsubscribe from bot detection alerts."
      description: "Delete a subscription from bot detection alerts.\n"
      operationId: "unsubscribeFromBotDetectionAlerts"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:admin_alert_manage"
  /system-scopes/{scopeName}:
    get:
      tags:
        - "System Scopes"
      summary: "Retrieve scopes for a particular user"
      description: "This operation will return the scope list of particular user\n\
        In order to get it, we need to pass the userId as a query parameter\n"
      operationId: "systemScopesScopeNameGet"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:scope_manage"
      x-wso2-curl: "curl -k -X GET \"https://localhost:9443/api/am/admin/v1/system-scopes/YXBpbTpzdWJzY3JpYmU?username=john\"\
        \ -H \"accept: application/json\" -H \"Authorization: Bearer 8e8edc50-4a70-3fec-af00-ce08097012ab"
      x-wso2-request: "GET https://localhost:9443/api/am/admin/v1/system-scopes/Base64urlEncode(apim:subscribe)?username=john\
        \ Authorization: Bearer 8e8edc50-4a70-3fec-af00-ce08097012ab"
      x-wso2-response: "{\n  \"name\":\"apim:subscribe\"  \n}\n"
  /system-scopes:
    get:
      tags:
        - "System Scopes"
      summary: "Get the list of role scope mapping.\n"
      description: "This operation is used to get the list of role scope mapping from\
        \ tenant-conf for the apim admin dashboard\n"
      operationId: "systemScopesGet"
      security:
        - OAuth2Security:
            - "apim:scope_manage"
            - "apim:admin"
    put:
      tags:
        - "System Scopes"
      summary: "Update Roles For Scope\n"
      description: "This operation is used to update the roles for all scopes\n"
      operationId: "updateRolesForScope"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:scope_manage"
  /system-scopes/role-aliases:
    get:
      tags:
        - "System Scopes"
      summary: "Retrieve role alias mappings"
      description: "This operation can be used to retreive role alias mapping\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:scope_manage"
    put:
      tags:
        - "System Scopes"
      summary: "Add a new role alias"
      description: "This operation can be used to add a new role alias mapping for\
        \ system scope roles\n"
      security:
        - OAuth2Security:
            - "apim:scope_manage"
            - "apim:admin"
  /tenant-theme:
    get:
      tags:
        - "Tenant Theme"
      summary: "Export a DevPortal Tenant Theme"
      description: "This operation can be used to export a DevPortal tenant theme\
        \ as a zip file.\n"
      operationId: "exportTenantTheme"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:tenant_theme_manage"
    put:
      tags:
        - "Tenant Theme"
      summary: "Import a DevPortal Tenant Theme"
      description: "This operation can be used to import a DevPortal tenant theme.\n"
      operationId: "importTenantTheme"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:tenant_theme_manage"
  /key-managers:
    get:
      tags:
        - "Key Manager (Collection)"
      summary: "Get all Key managers"
      description: "Get all Key managers\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:admin_operations"
    post:
      tags:
        - "Key Manager (Collection)"
      summary: "Add a new API Key Manager"
      description: "Add a new API Key Manager\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:admin_operations"
  /key-managers/{keyManagerId}:
    get:
      tags:
        - "Key Manager (Individual)"
      summary: "Get a Key Manager Configuration"
      description: "Retrieve a single Key Manager Configuration. We should provide\
        \ the Id of the KeyManager as a path parameter.\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:admin_operations"
    put:
      tags:
        - "Key Manager (Individual)"
      summary: "Update a Key Manager"
      description: "Update a Key Manager by keyManager id\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:admin_operations"
    delete:
      tags:
        - "Key Manager (Individual)"
      summary: "Delete a Key Manager"
      description: "Delete a Key Manager by keyManager id\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:admin_operations"
  /key-managers/discover:
    post:
      tags:
        - "Key Manager (Collection)"
      summary: "Retrieve Well-known information from KeyManager Well-known Endpoint."
      description: "Get all Key managers\n"
      security:
        - OAuth2Security:
            - "apim:admin"
            - "apim:admin_operations"
securityDefinitions:
  OAuth2Security:
    type: "oauth2"
    tokenUrl: "https://localhost:9443/oauth2/token"
    flow: "password"
    scopes:
      openid: "Authorize access to user details"
      apim:admin: "Manage all admin operations"
      apim:tier_view: "View throttling policies"
      apim:tier_manage: "Update and delete throttling policies"
      apim:bl_view: "View deny policies"
      apim:bl_manage: "Update and delete deny policies"
      apim:mediation_policy_view: "View mediation policies"
      apim:mediation_policy_create: "Create and update mediation policies"
      apim:app_owner_change: "Retrieve and manage applications"
      apim:app_import_export: "Import and export applications related operations"
      apim:api_import_export: "Import and export APIs related operations"
      apim:api_product_import_export: "Import and export API Products related operations"
      apim:label_manage: "Manage microgateway labels"
      apim:label_read: "Retrieve microgateway labels"
      apim:monetization_usage_publish: "Retrieve and publish Monetization related\
        \ usage records"
      apim:api_workflow_approve: "Manage workflows"
      apim:bot_data: "Retrieve bot detection data"
      apim:tenantInfo: "Retrieve tenant related information"
      apim:tenant_theme_manage: "Manage tenant themes"
      apim:admin_operations: "Manage API categories"
      apim:admin_settings: "Retrieve admin settings"
      apim:admin_alert_manage: "Manage admin alerts"
      apim:api_workflow_view: "Retrive workflow requests"
      apim:scope_manage: "Manage scope"