CREATE USER acl WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

CREATE SCHEMA acl_data AUTHORIZATION rudi;
GRANT ALL ON SCHEMA acl_data TO acl;
ALTER USER acl SET search_path TO acl_data, public;
