ARG BASE_IMAGE_TAG=latest
FROM glregistry.boost.open.global/rennes-metropole/rudi/rudi/microservice:$BASE_IMAGE_TAG

ADD rudi-microservice-projekt-facade.jar /opt/rudi/microservice.jar
ADD log4j2.xml /etc/rudi/config/microservice/log4j2.xml
