package org.rudi.common.test;

import org.assertj.core.api.AbstractListAssert;
import org.assertj.core.api.ObjectAssert;
import org.springframework.http.ResponseEntity;
import org.springframework.test.util.ReflectionTestUtils;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

public class RudiResponseEntityAssert<T> extends RudiObjectAssert<ResponseEntity<T>> {
	public RudiResponseEntityAssert(ResponseEntity<T> actual) {
		super(actual);
	}

	public RudiResponseEntityAssert<T> hasNoErrorStatus() {
		assertThat(actual.getStatusCode().isError()).isFalse();
		return this;
	}

	/**
	 * Useful to do assertions on objects that were generated by openapi-generator-maven-plugin and consequently has a list field named "items".
	 */
	@SuppressWarnings("java:S1452") // le type de retour dépend de org.assertj.core.api.AbstractAssert.asList
	public AbstractListAssert<?, List<?>, Object, ObjectAssert<Object>> asItemsList() {
		final T body = actual.getBody();
		assertThat(body)
				.isNotNull()
				.hasFieldOrProperty("items");

		final Object items = ReflectionTestUtils.getField(body, "items");
		return assertThat(items).asList();
	}
}
